### ISSUE TITLE
Make changelogs not explode when we add a T-Epic label

### ISSUE THREAD

**Issue by kittykat** [matrix-org/allchange#38]
The T-Epic label should probably be ignored by this project as either it will have a T-Defect/T-Enhancement label or child issues with those labels.

**Comment by daniellekirkwood** [comment]
@kittykat Does this break the release process or make it more complex?

Or, is this fixed already? 😍

**Comment by kittykat** [comment]
@daniellekirkwood As far as I'm aware, this is still waiting for the web team's attention. Apparently if I add a T-Epic label to the element-web repo right now, it will break changelogs for releases

**Comment by daniellekirkwood** [comment]
Thanks, @kittykat 

@andybalaam can we chat about what next steps might be and what a fix might look like? Is this something that the Web Chapter can help us with as this impacts us all?

**Comment by Johennes** [comment]
@t3chguy I believe you have most context on this. This has been open for a while and I believe we've used `T-Epic` without things going wrong?

**Comment by kittykat** [comment]
@Johennes We have on all other repos, but not in element-web for this specific reason. It would be good to bring web in line with everything else.

**Comment by Johennes** [comment]
Sorry, I could have sworn I've seen `T-Epic` on our epics but I must have mixed that up. 🤦‍♂️

@t3chguy I suspect we will have to touch allchange as part of the release automation project? If so and unless this would be a real quickie, I think it's sufficient to include this change then since it's a consistency annoyance but not really blocking anything right now.

**Comment by t3chguy** [comment]
The `T-` labels decide where something lives in the [changelog](https://github.com/vector-im/element-web/releases)

T-Defect: Bug Fixes
T-Enhancement: Features
T-Task: Omit entirely

T-Epic would be where in that?

**Comment by Johennes** [comment]
Hold on, allchange builds the changelog from commits / PRs, right? I think you wouldn't normally close an epic with a PR because the whole point of an epic is to act as a container for other issues. So normally an epic should only be closed manually in which case it'd not show up in the changelog regardless of labels?

**Comment by t3chguy** [comment]
True, but allchange's definition is to accept any `T-*` label - https://github.com/matrix-org/allchange/blob/f03b5198876d5062d9f0114d1816b3ef45f6f66d/action.yml#L11

**Comment by andybalaam** [comment]
```
T-Epic: Omit entirely
```

Gets my vote then.

**Comment by t3chguy** [comment]
> If so and unless this would be a real quickie

@Johennes it would be

**Comment by Johennes** [comment]
Then let's just do it. I'll add it into the [Q1 – Other](https://github.com/orgs/vector-im/projects/67/views/31) view.

**Comment by t3chguy** [comment]
Should be fine to use `T-Epic` on issues even without the above change, using them on pull requests is invalid and may yield unexpected results. PR updates documentation to exclude T-Epic
